### ISSUE TITLE
When I edited 'zh_CN.yml', I got error

### ISSUE THREAD

**Issue by JuChanMin** [lt-name/GunWar_Nukkit#24]
I edited Chinese to Korean

---zh_CN.yml---

useCmdInRoom: "§e >>§c게임에서 다른 명령을 사용할 수 없습니다"
cmdHelp: "§a 보기 도움말: /%cmdName% help"
userHelp: "§eGunWar--명령 도움말\n §a/%cmdName% ui §e를 열어 ui \n §a/%cmdName% join 룸 이름 §e 가입 게임 \n § a/%cmdName% quit 탈퇴 게임 \n §a/%cmdName% list 룸 리스트 보기
noPermission: "§c 당신은 이 명령을 사용할 권한이 없습니다!"
joinRoom: "§a님 방 가입했습니다: %name%"
joinRoomIsInRoom: "§c 너는 이미 한 방에 있어!"
joinRoomIsRiding: "§a는 탑승 상태에서 방에 들어가지 마십시오!"
joinRandomRoom: "§a는 이미 당신을 위해 무작위로 방을 할당했습니다!"
joinRoomIsPlaying: "§a 이 방이 게임중이니 잠시만 기다려주세요"
joinRoomIsFull: "§a 이 방이 꽉 찼으니 잠시만 기다려주세요"
joinRoomIsNotFound: "§a 이 방은 존재하지 않습니다!"
joinRoomNotAvailable: "§a는 사용 가능한 방이 없습니다!"
quitRoom: "§a씨는 방에서 나가셨습니다"
quitRoomNotInRoom: "§a씨는 원래 게임방에 없어요!"
listRoom: "§e 룸 리스트: §a %list%"
useCmdInCon: "제어 콘솔에서 이 명령어를 실행하지 마십시오!"
adminHelp: "§eGunWar--명령 도움말 \n §a/%cmdName% ui §e를 열어 ui \n § a/%cmdName% setwaitspawn §e를 대기점 \n § a/%cmdName% setredspawn §e로 설정하기에 충분함 wawaitspawn §)etgametime 숫자 §e를 사용하여 게임당 최대 시간 \n 설정 §a/%cmdName% reloadroom §e중재소방이 있습니다 \n §a/%cmdName% unloadroom §e관모든 방을 닫고 하역 배치"
adminSetWaitSpawn: "§a는 출생점 설정이 완료될 때까지 기다립니다!"
adminSetRedSpawn: "§a 레드 팀 출생점 설정 성공!"
adminSetBlueSpawn: "§a블루 팀 출생점 설정 성공!"
adminNotNumber: "§a 시간은 양수로만 설정할 수 있습니다!"
adminSetWaitTime: "§a 대기 시간이 다음 %time%로 설정되었습니다."
adminSetGameTime: "§a 게임 시간이 다음 %time%로 설정되었습니다."
adminSetGameTimeShort: "§a 게임 시간을 최소 미만으로 설정할 수 없음1분!"
adminReload: "§a 배치 재연결 완료!백그라운드에서 정보를 보십시오!"
adminUnload: "§a가 모든 방을 하역했습니다!백그라운드에서 정보를 보십시오!"
playerTeamSelect: "당신은 이미 팀을 선택했습니다."
roomSafeKick: "\n§c 방이 비정상적으로 닫혔습니다!\n님을 위한 백팩 안착전, 잠시 후에 서버를 재진입하십시오!"
noTeamSelect: "팀 선택 안 함"
teamNameRed: "§c레드 팀"
teamNameBlue: "§9블루팀"
roundVictoryRed: "§c레드팀이 이번 라운드에서 승리"
roundVictoryBlue: "§9블루팀이 이번 라운드에서 승리"
victoryRed: "§c홍팀 승리"
victoryBlue: "§9블루팀 승리"
roundVictoryDraw: "플랫폼"
titleDeathTitle: "죽음"
titleDeathSubtitle: "당신은 %player%에 의해 격살되었습니다"
killMessage: "§e >> §c%damagePlayer% %player%"을(를) 죽였습니다.
tpJoinRoomLevel: "§e >> cc를 게임 지도에 들어가려면 먼저게임에 가입하세요!"
tpQuitRoomLevel: "§e >>>c를 방에서 탈퇴하려면 명령을 사용하십시오!"
gameArmor: "§e >> §c게임에서는 호갑을 벗을 수 없습니다!"
playerTeamChat: "§c[팀] %player% + §b >> %message%"
scoreBoardTitle: "§eGunWar"
waitTimeScoreBoard: " 소속 팀: %team% \n 플레이어: §a %playerNumber%/10 \n §a 시작카운트다운: §e%time% "
waitScoreBoard: " 소속 팀: %team%\n 플레이어: §a %playerNumber%/10 \n 최소 게임인원 2인 \n 플레이어가 가입하기를 기다리는 중 "
waitTimeBottom: "§a가 현재 이미 있습니다: %playerNumber% 플레이어 \n §a 게임 그리고 다음과 같이 %time% 초 시작!
waitBottom: "§c는 플레이어가 가입하기를 기다리는 중이고 현재 이미 있습니다: %playerNumber% 플레이어"
gameTimeScoreBoard: " §l§a에 속한 행렬: %team% \n §l§a 현재 혈량:: e %health% \n §l§a남은 시간: §e %time% 초 \n 의 행렬 생존 인원: \n §l§c红: %red%인 99청: %blue%
gameTimeBottom: "§l§c 혈량: %health%"
victoryMessage: "§e 축하 %teamName% §e획득승리하다"
userMenuButton1 : "§e 랜덤으로 방에 가입"
userMenuButton2: "§e를 현재 방에서 탈퇴"
userMenuButton3: "§e 방 목록 보기"
userMenuButton4: "§e 전적 차트 보기"
adminMenuSetLevel: "현재 지도 설정: %name%"
adminMenuButton1: "§e 설정 대기생점"
adminMenuButton2: "§e 홍대생점 설정"
adminMenuButton3: "§e에 블루팀 출생점 설정"
adminMenuButton4: "§e 설정 시간 파라미터"
adminMenuButton5: "§e중재 모든 방"
adminMenuButton6: "§c는 모든 방을 하역합니다"
adminTimeMenuInputText1: "대기 시간(초)"
adminTimeMenuInputText2: "게임 시간(초)"
joinRoomOK: "§l§a가 룸에 가입할 것을 확인했습니다: %name% §l§a?"
buttonOK: "§a 확정"
buttonReturn: "§c 리턴"
recordListButton1 : "§e개인전적보기"
recordListButton2: "§e 격살 차트 보기"
recordListButton3: "§e 사망 차트 보기"
recordListButton4: "§e 승리 차트 보기"
recordListButton5: "§e 보기 실패 차트"
killsRanking: "클릭 차트: "
deathsRanking: "죽음 차트: "
victoryRanking: "승리 횟수 차트: "
defeatRanking: "실패 횟수 차트: "
ranking: "Top%ranking% 플레이어: %player%" 횟수: %number%"
playerGameRecord: " 격살 수: %kills%\n 사망 수: %deaths%\n 승리 횟수: %victory%\n 실패 횟수: %defeat%"
itemQuitRoom: "§c를 방에서 퇴출"
itemQuitRoomLore: "손을 들고 클릭하면 룸에서 탈퇴"
itemTeamSelectRed: "§c는 레드팀을 선택합니다"
itemTeamSelectBlue: "§9에 블루팀 선택"
itemGrenade: "§a 수류탄"
itemGrenadeLore: "상해: 2-10 \n 상해 반지름: 5"
itemFlashBang: "§a 섬광탄"
itemFlashBangLore: "짧은 실명 효과 \n 유효 반지름: 5"

----------

and I started my server

---console---

09:43:45 [INFO ] GunWar v1.0.0-SNAPSHOT을(를) 활성화 중입니다
09:43:45 [INFO ] [GunWar] 插件开始加载！本插件是免费哒~如果你花钱了，那一定是被骗了~
09:43:45 [INFO ] [GunWar] 版本: 1.0.0-SNAPSHOT git-30dbde1
09:43:45 [INFO ] [GunWar] 开始加载资源文件
09:43:45 [INFO ] [GunWar] Language: zh_CN loaded !
09:43:45 [ERROR] Throwing
java.lang.RuntimeException: while parsing a block mapping
 in 'string', line 1, column 1:
    useCmdInRoom: "§e >>§c게임에서 다른 명령 ... 
    ^
expected <block end>, but found Scalar
 in 'string', line 4, column 16:
    noPermission: "§c 당신은 이 명령을 사용할 권한이 없습니다!"
                   ^
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:741) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:730) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:566) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 1, column 1:
    useCmdInRoom: "§e >>§c게임에서 다른 명령 ... 
    ^
expected <block end>, but found Scalar
 in 'string', line 4, column 16:
    noPermission: "§c 당신은 이 명령을 사용할 권한이 없습니다!"
                   ^
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.utils.Config.parseContent(Config.java:554) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.utils.Config.load(Config.java:160) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.utils.Config.<init>(Config.java:98) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.utils.Config.<init>(Config.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.lanink.gunwar.GunWar.loadResources(GunWar.java:170) ~[?:?]
        at cn.lanink.gunwar.GunWar.onEnable(GunWar.java:60) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
09:43:45 [INFO ] GunWar v1.0.0-SNAPSHOT을(를) 비활성화 중입니다
09:43:45 [INFO ] [GunWar] 插件卸载完成！

---------

I try founded error, But I cant find :c
Can you help me?

**Comment by lt-name** [comment]
The configuration file is in yaml format, there may be some formatting problems in your language file.
If you can, please upload your language file so that I can troubleshoot the problem.
(Google Translate)

**Comment by JuChanMin** [comment]
I don't know much about Github.
But I hope the language file I made was delivered to you well :)
